//
//  UIColor+AWAdditions.swift
//
//  Generated by Zeplin on 9/7/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class func awSunYellowColor() -> UIColor {
		return UIColor(red: 248.0 / 255.0, green: 231.0 / 255.0, blue: 28.0 / 255.0, alpha: 1.0)
	}

	class func awScarletColor() -> UIColor {
		return UIColor(red: 208.0 / 255.0, green: 2.0 / 255.0, blue: 27.0 / 255.0, alpha: 1.0)
	}

	class func awSquashColor() -> UIColor {
		return UIColor(red: 245.0 / 255.0, green: 166.0 / 255.0, blue: 35.0 / 255.0, alpha: 1.0)
	}

	class func awDarkGrassGreenColor() -> UIColor {
		return UIColor(red: 65.0 / 255.0, green: 117.0 / 255.0, blue: 5.0 / 255.0, alpha: 1.0)
	}

	class func awDarkSkyBlueColor() -> UIColor {
		return UIColor(red: 74.0 / 255.0, green: 144.0 / 255.0, blue: 226.0 / 255.0, alpha: 1.0)
	}

	class func awVioletColor() -> UIColor {
		return UIColor(red: 189.0 / 255.0, green: 16.0 / 255.0, blue: 224.0 / 255.0, alpha: 1.0)
	}

	class func awLightSageColor() -> UIColor {
		return UIColor(red: 184.0 / 255.0, green: 233.0 / 255.0, blue: 134.0 / 255.0, alpha: 1.0)
	}
}
